version: '3'

services:
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        restart: always
        volumes:
            - db:/var/mysql
        expose:
            - "3306"
        networks:
            - intra
        tty: true
    wordpress:
        container_name: wordpress
        build: requirements/wordpress/
        restart: always
        volumes:
            - data:/var/www/html
        expose:
            - "9000"
        env_file:
            - .env
        networks:
            - intra
        tty: true
        depends_on:
            - mariadb
    nginx:
        container_name: nginx
        build: requirements/nginx/
        restart: always
        ports:
            - "443:443"
        volumes:
            - data:/var/www/html
        networks:
            - intra
        tty: true
        depends_on:
            - wordpress
volumes:
    - data: /home/hekang/data
    - db: /home/hekang/db
networks:
    intra:
        driver: bridge
