version: '3'

services:
    mariadb:
        container_name: mariadb
        build: "./requirements/mariadb"
        restart: always
        volumes:
            - db:/var/mysql
        env_file:
            - .env
        expose:
            - "3306"
        networks:
            - intra
        tty: true
    wordpress:
        container_name: wordpress
        build: "./requirements/wordpress/"
        restart: always
        volumes:
            - wp:/var/www/html
        expose:
            - "9000"
        env_file:
            - .env
        networks:
            - intra
        tty: true
        depends_on:
            - mariadb
    nginx:
        container_name: nginx
        build: "./requirements/nginx/"
        restart: always
        ports:
            - "443:443"
        volumes:
            - wp:/var/www/html
        networks:
            - intra
        tty: true
        depends_on:
            - wordpress
volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
    #   device: '/home/hekang/data/wp'
      device: '/Users/hekang/Desktop/Inception/wp'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
    #   device: '/home/hekang/data/db'
      device: '/Users/hekang/Desktop/Inception/db'

networks:
    intra:
        driver: bridge
